# Default squrl theme - Blue/Gray dark theme

[UI]
font_color = "Blue"
main_foreground_color = "Blue"
secondary_foreground_color = "DarkGray"
main_background_color = "DarkGray"
secondary_background_color = { Rgb = [50, 50, 50] }
separator_color = "Gray"

[Others]
selection_highlight_color = "Yellow"
environment_variable_highlight_color = "Cyan"

[HTTP.Methods]
GET = "Green"
POST = "Yellow"
PUT = "LightBlue"
PATCH = "LightCyan"
DELETE = "LightRed"
HEAD = "Green"
OPTIONS = "Magenta"
TRACE = "Yellow"
CONNECT = "LightBlue"

[Websocket.connection_status]
connected = "Green"
disconnected = "Red"

[Websocket.messages]
server_foreground_color = "Blue"
server_background_color = "DarkGray"
you_background_color = "Blue"
details_color = "DarkGray"
